/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;

/**
 *
 * @author Wahyu
 */
public class InvoiceForm extends javax.swing.JFrame {
    private boolean isEditMode = false;
    private String currentEditingInvoice = null;
    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents(); // WAJIB: Initialize components first
        setLocationRelativeTo(null);
        tampilInvoice(txtCariInvoice.getText()); // Then load data
    }
    
    private void tampilInvoice(String cari) {
        List<Invoice> daftar = Invoice.getDataInvoice(cari);
        String[] kolom = {"No. Invoice", "No. Sales Order", "No. Pembayaran", "Tgl.Invoice", "Tgl.Jatuh Tempo"};

        DefaultTableModel model = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // semua kolom tidak bisa diedit langsung
            }
        };
        
        // Add data to table model
    for (Invoice p : daftar) {
        Object[] row = {
            p.noInvoice,
            p.noSO,
            p.tanggalInvoice,
            p.tanggalJatuhTempo,
        };
        model.addRow(row);
    }
        
        tblInvoice.setModel(model);
    } // FIXED: Proper closing bracket for tampilInvoice method

      public void setFormMode(Boolean flag){
         txtNoInvoice.setEnabled(flag);
        txtSalesOrder.setEnabled(flag);
        txtPembayaran.setEnabled(flag);
        TglInvoice.setEnabled(flag);
        TglJatuhTempo.setEnabled(flag);
        btnSimpanInvoice.setEnabled(flag);
        btnResetInvoice.setEnabled(flag);
        
        btnUbahInvoice.setEnabled(!flag);
        btnTambahInvoice.setEnabled(!flag);
        btnHapusInvoice.setEnabled(!flag);
        
         if (!flag) {
        // Hapus isi form saat nonaktif
       clearForm();
    }
   }
   
   public void clearForm(){
       txtNoInvoice.setText("");
         txtSalesOrder.setText("");
        txtPembayaran.setText("");
        TglInvoice.setDate(null); // asumsi index 0 adalah default
        TglJatuhTempo.setDate(null);
      
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataInvoice = new javax.swing.JPanel();
        txtCariInvoice = new javax.swing.JTextField();
        btnCariInvoice = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNoInvoice = new javax.swing.JTextField();
        txtSalesOrder = new javax.swing.JTextField();
        txtPembayaran = new javax.swing.JTextField();
        TglInvoice = new com.toedter.calendar.JDateChooser();
        TglJatuhTempo = new com.toedter.calendar.JDateChooser();
        btnUbahInvoice = new javax.swing.JButton();
        btnTambahInvoice = new javax.swing.JButton();
        btnHapusInvoice = new javax.swing.JButton();
        btnSimpanInvoice = new javax.swing.JButton();
        btnResetInvoice = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCariInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariInvoiceActionPerformed(evt);
            }
        });

        btnCariInvoice.setText("Cari");
        btnCariInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariInvoiceActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Data Invoice");

        jLabel32.setText("Cari Nama :");

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Invoice", "No. Sales Order", "No. Pembayaran", "Tgl.Invoice", "Tgl.Jatuh Tempo"
            }
        ));
        jScrollPane1.setViewportView(tblInvoice);

        jLabel29.setText("No. Invoice :");

        jLabel30.setText("No. Sales Order :");

        jLabel27.setText("Tgl. Jatuh Tempo :");

        jLabel28.setText("Tgl. Invoice :");

        jLabel26.setText("No. Pembayaran :");

        txtNoInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoInvoiceActionPerformed(evt);
            }
        });

        btnUbahInvoice.setText("Ubah");
        btnUbahInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahInvoiceActionPerformed(evt);
            }
        });

        btnTambahInvoice.setText("Tambah");
        btnTambahInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahInvoiceActionPerformed(evt);
            }
        });

        btnHapusInvoice.setText("Hapus");
        btnHapusInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusInvoiceActionPerformed(evt);
            }
        });

        btnSimpanInvoice.setText("Simpan");
        btnSimpanInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanInvoiceActionPerformed(evt);
            }
        });

        btnResetInvoice.setText("Reset");
        btnResetInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataInvoiceLayout = new javax.swing.GroupLayout(dataInvoice);
        dataInvoice.setLayout(dataInvoiceLayout);
        dataInvoiceLayout.setHorizontalGroup(
            dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataInvoiceLayout.createSequentialGroup()
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataInvoiceLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txtSalesOrder)
                            .addComponent(txtNoInvoice))
                        .addGap(97, 97, 97)
                        .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataInvoiceLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TglJatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dataInvoiceLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(TglInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSimpanInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataInvoiceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataInvoiceLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCariInvoice)
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataInvoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnResetInvoice)
                    .addGroup(dataInvoiceLayout.createSequentialGroup()
                        .addComponent(btnTambahInvoice)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbahInvoice)))
                .addGap(18, 18, 18)
                .addComponent(btnHapusInvoice)
                .addGap(18, 18, 18))
        );
        dataInvoiceLayout.setVerticalGroup(
            dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataInvoiceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariInvoice))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbahInvoice)
                    .addComponent(btnHapusInvoice)
                    .addComponent(btnTambahInvoice))
                .addGap(18, 18, 18)
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txtNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addComponent(TglInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(txtSalesOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addComponent(TglJatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataInvoiceLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dataInvoiceLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dataInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanInvoice)
                            .addComponent(btnResetInvoice))))
                .addGap(22, 22, 22))
        );

        jButton1.setText("Print");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali)
                    .addComponent(btnRefresh))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(btnKembali)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(8, 63, 115));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 80));

        btnLogout.setBackground(new java.awt.Color(236, 236, 233));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, Username");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SBA Logistik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel25)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(dataInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(dataInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoInvoiceActionPerformed

    private void btnCariInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariInvoiceActionPerformed
        tampilInvoice(txtCariInvoice.getText());
    }//GEN-LAST:event_btnCariInvoiceActionPerformed

    private void txtCariInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariInvoiceActionPerformed
        tampilInvoice(txtCariInvoice.getText());
    }//GEN-LAST:event_txtCariInvoiceActionPerformed

private void btnSimpanInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanInvoiceActionPerformed
//  try {
//            // FIXED: Validate required fields
//            if (txtNoInvoice.getText().trim().isEmpty()) {
//                JOptionPane.showMessageDialog(this, "No. Invoice tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//            
//            if (TglInvoice.getDate() == null || TglJatuhTempo.getDate() == null) {
//                JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//            
//            java.sql.Date sqlTglInvoice = new java.sql.Date(TglInvoice.getDate().getTime());
//            java.sql.Date sqlTglJatuhTempo = new java.sql.Date(TglJatuhTempo.getDate().getTime());
//
//            // FIXED: Logic for CREATE vs UPDATE
//            Invoice inv = new Invoice(
//                txtNoInvoice.getText().trim(), 
//                txtSalesOrder.getText().trim(),
//                txtPembayaran.getText().trim(),
//                sqlTglInvoice,
//                sqlTglJatuhTempo
//            );
//            
//            // Check if this is a new invoice or update existing one
//            // You might need to add a flag or check if invoice exists
//            boolean isNewInvoice = true; // You should implement proper logic here
//            
//            if (isNewInvoice) {
//                inv.createInvoice();
//                JOptionPane.showMessageDialog(this, "Invoice berhasil disimpan", "Info", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                inv.updateInvoice();
//                JOptionPane.showMessageDialog(this, "Invoice berhasil diperbarui", "Info", JOptionPane.INFORMATION_MESSAGE);
//            }
//
//            setFormMode(false);
//            tampilInvoice(txtCariInvoice.getText()); // Refresh table after save
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
}//GEN-LAST:event_btnSimpanInvoiceActionPerformed


    private void btnTambahInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahInvoiceActionPerformed
 // TODO add your handling code here:
                        clearForm();

        setFormMode(true);
    }//GEN-LAST:event_btnTambahInvoiceActionPerformed

    private void btnUbahInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahInvoiceActionPerformed
        // TODO: Implement edit functionality
            System.out.println("Ubah button clicked"); // Debug line
        int selectedRow = tblInvoice.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        isEditMode = true; // Set to edit mode
        setFormMode(true); // Enable form for editing
        
        // Load selected data to form fields
        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        currentEditingInvoice = model.getValueAt(selectedRow, 0).toString();
        
        txtNoInvoice.setText(model.getValueAt(selectedRow, 0).toString());
        txtSalesOrder.setText(model.getValueAt(selectedRow, 1).toString());
        txtPembayaran.setText(model.getValueAt(selectedRow, 2).toString());
        
        // Handle date parsing
        try {
            if (model.getValueAt(selectedRow, 3) != null) {
                java.sql.Date tglInv = (java.sql.Date) model.getValueAt(selectedRow, 3);
                TglInvoice.setDate(new java.util.Date(tglInv.getTime()));
            }
            if (model.getValueAt(selectedRow, 4) != null) {
                java.sql.Date tglJatuhTempo = (java.sql.Date) model.getValueAt(selectedRow, 4);
                TglJatuhTempo.setDate(new java.util.Date(tglJatuhTempo.getTime()));
            }
        } catch (Exception e) {
            System.out.println("Error parsing dates: " + e.getMessage());
        }
        
        // Disable invoice number field during edit (primary key shouldn't change)
        txtNoInvoice.setEnabled(false);
    }//GEN-LAST:event_btnUbahInvoiceActionPerformed

    private void btnHapusInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusInvoiceActionPerformed
        // TODO: Implement delete functionality
     System.out.println("Hapus button clicked"); // Debug line
        int selectedRow = tblInvoice.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get invoice number from selected row
        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
        String noInvoice = model.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus Invoice: " + noInvoice + "?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
            
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Invoice.deleteInvoice(noInvoice);
                tampilInvoice(txtCariInvoice.getText()); // Refresh table
                JOptionPane.showMessageDialog(this, "Invoice berhasil dihapus!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusInvoiceActionPerformed

    private void btnResetInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetInvoiceActionPerformed
         // TODO add your handling code here:
                setFormMode(false);
    }//GEN-LAST:event_btnResetInvoiceActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
         System.out.println("Refresh button clicked"); // Debug line
        tampilInvoice(txtCariInvoice.getText());
        JOptionPane.showMessageDialog(this, "Data berhasil di-refresh!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    PenjualanMenu penjualan = new PenjualanMenu();
        penjualan.setVisible(true);
         dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda ingin logout?",
            "Logout",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TglInvoice;
    private com.toedter.calendar.JDateChooser TglJatuhTempo;
    private javax.swing.JButton btnCariInvoice;
    private javax.swing.JButton btnHapusInvoice;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnResetInvoice;
    private javax.swing.JButton btnSimpanInvoice;
    private javax.swing.JButton btnTambahInvoice;
    private javax.swing.JButton btnUbahInvoice;
    private javax.swing.JPanel dataInvoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtCariInvoice;
    private javax.swing.JTextField txtNoInvoice;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtSalesOrder;
    // End of variables declaration//GEN-END:variables
}