/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author LOVIANNO
 */
public class LaporanMenu extends javax.swing.JFrame {

    /**
     * Creates new form LaporanMenu
     */
    public LaporanMenu() {
     initComponents();
     
     lblUsername.setText(Login.nama);
     txtTanggalAwal.setDate(DateNow);
     txtTanggalAkhir.setDate(DateNow);
// java.sql.Date today = new java.sql.Date(System.currentTimeMillis());
    tampilkanSalesOrder(DateNow, DateNow, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated bys the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnKembali2 = new javax.swing.JButton();
        cardProduk = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnCariLaporan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesOrder = new javax.swing.JTable();
        cbSorting = new javax.swing.JComboBox<>();
        txtTanggalAkhir = new com.toedter.calendar.JDateChooser();
        lblTo = new javax.swing.JLabel();
        txtTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        lblJual = new javax.swing.JLabel();
        lblBeli = new javax.swing.JLabel();
        lblLaba = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(8, 63, 115));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 80));

        btnLogout.setBackground(new java.awt.Color(236, 236, 233));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, Username");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SBA Logistik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel25)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(8, 63, 115));

        btnKembali2.setText("Kembali");
        btnKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnKembali2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnKembali2)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        cardProduk.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Laporan Laba");

        btnCariLaporan.setText("Cari");
        btnCariLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariLaporanActionPerformed(evt);
            }
        });

        tblSalesOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No SO", "Tanggal", "Asal", "Tujuan", "Customer", "Supplier", "Status"
            }
        ));
        tblSalesOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalesOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalesOrder);

        cbSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harian", "Bulanan", "Tahunan" }));
        cbSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSortingActionPerformed(evt);
            }
        });

        txtTanggalAkhir.setDateFormatString("d MMM yyyy");

        lblTo.setText("To");

        txtTanggalAwal.setDateFormatString("d MMM yyyy");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Total Harga Beli :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah Sales Order :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Total Harga Jual :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Total Laba :");

        lblJumlah.setText("0");

        lblJual.setText("0");

        lblBeli.setText("0");

        lblLaba.setText("0");

        javax.swing.GroupLayout cardProdukLayout = new javax.swing.GroupLayout(cardProduk);
        cardProduk.setLayout(cardProdukLayout);
        cardProdukLayout.setHorizontalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addComponent(cbSorting, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardProdukLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel14))
                            .addGroup(cardProdukLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cardProdukLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblJual, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cardProdukLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cardProdukLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblLaba, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardProdukLayout.setVerticalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCariLaporan)
                    .addComponent(txtTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTo))
                    .addComponent(txtTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblJumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBeli)
                    .addComponent(jLabel4)
                    .addComponent(lblLaba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblJual))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 479, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private long totalJual = 0, totalBeli = 0, totalLaba = 0;
    private int totalData = 0;
    Date DateNow = new Date(System.currentTimeMillis());

    private void tampilkanHasilPerhitungan(){
    NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

    // Jumlah (tidak perlu format Rupiah, misal ini count saja)
    lblJumlah.setText(String.valueOf(totalData));

    // Beli, Jual, dan Laba pakai format Rupiah
    lblBeli.setText(rupiah.format(totalBeli));
    lblJual.setText(rupiah.format(totalJual));

    long totalLaba = totalJual - totalBeli;
    lblLaba.setText(rupiah.format(totalLaba));
    
    }
    
    private void tampilkanSalesOrder(Date fromDate, Date toDate, Integer status) {
    // 1) Ambil data berdasar rentang tanggal dan status
    List<SalesOrder> daftar = SalesOrder.getSalesOrderToLaporan(fromDate, toDate, status);

    // 2) Siapkan kolom untuk JTable
    String[] kolom = {
        "No", "Nomor SO", "Tanggal", "Asal", "Tujuan",
        "Customer", "Supplier",  "Status"
    };
    DefaultTableModel model = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
        // Hitung total berdasarkan field hargaTotal di SO
//        long totalSO = so.getHargaTotal();

        // Hitung total harga jual berdasarkan detailOrders:
        
    
    // 3) Isi baris per SalesOrder
    int no = 1;
    for (SalesOrder so : daftar) {
        
        
        String statusText = so.status == 0 ? "Belum Selesai" : "Selesai";
        model.addRow(new Object[]{
            no++,
            so.noSO,
            so.tanggal,
            so.dikirimDari,
            so.tujuan,
      so.getCustomers().isEmpty() ? "-" : so.getCustomers().get(0).nama,
      so.getSuppliers().isEmpty() ? "-" : so.getSuppliers().get(0).nama,
            statusText
            
        });
        totalData = no;
        for (DetailOrder det : so.getDetailOrders()) {
            totalBeli += det.kuantitas * det.hargaBeli;
            totalJual += det.kuantitas * det.hargaJual;
            
        };
        
    }
        if(daftar.isEmpty()){
            totalBeli = 0;
            totalJual = 0;
            totalData = 0;
            totalBeli = 0;
            
        }
                       tampilkanHasilPerhitungan();


    // 4) Pasang model ke tabel, atur lebar kolom No
    tblSalesOrder.setModel(model);
    tblSalesOrder.getColumnModel().getColumn(0).setMinWidth(30);
    tblSalesOrder.getColumnModel().getColumn(0).setMaxWidth(30);
}

    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda ingin logout?",
            "Logout",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    private void clearForm(){

//        txtTanggalAkhir.setDate(null);
    

    

     
    }
    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
        Dashboard db = new Dashboard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembali2ActionPerformed

    private void btnCariLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariLaporanActionPerformed
        // TODO add your handling code here:
        totalJual = 0;
                totalBeli = 0;
                
         java.util.Calendar cal = java.util.Calendar.getInstance();
    java.util.Date utilFrom, utilTo;

    switch (cbSorting.getSelectedIndex()) {
        case 0: // Harian: pakai kedua date chooser
            utilFrom = txtTanggalAwal.getDate();
            utilTo   = txtTanggalAkhir.getDate();
            break;

        case 1: // Bulanan: tanggal awal = hari pertama bulan, tanggal akhir = hari terakhir bulan
            utilFrom = txtTanggalAwal.getDate();
            cal.setTime(utilFrom);
            cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
            utilFrom = cal.getTime();
            cal.set(java.util.Calendar.DAY_OF_MONTH, cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH));
            utilTo   = cal.getTime();
            break;

        case 2: // Tahunan: tanggal awal = 1 Jan, tanggal akhir = 31 Des tahun yang dipilih
            utilFrom = txtTanggalAwal.getDate();
            cal.setTime(utilFrom);
            int year = cal.get(java.util.Calendar.YEAR);
            cal.set(year, java.util.Calendar.JANUARY,   1);
            utilFrom = cal.getTime();
            cal.set(year, java.util.Calendar.DECEMBER, 31);
            utilTo   = cal.getTime();
            break;

        default:
            utilFrom = txtTanggalAwal.getDate();
            utilTo   = txtTanggalAkhir.getDate();
    }

    // Konversi ke java.sql.Date
    Date fromDate = new Date(utilFrom.getTime());
    Date toDate   = new Date(utilTo.getTime());

    // Panggil DAO dengan rentang dan status (null = semua status)
    tampilkanSalesOrder(fromDate, toDate, 1);
  

    }//GEN-LAST:event_btnCariLaporanActionPerformed

    private void tblSalesOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalesOrderMouseClicked
        

    }//GEN-LAST:event_tblSalesOrderMouseClicked

    private void cbSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSortingActionPerformed
        // TODO add your handling code here:
        if(cbSorting.getSelectedIndex() == 0){
             SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy");
         txtTanggalAwal.setDateFormatString("d MMMMM yyyy");
         txtTanggalAwal.setDate(DateNow);
                  txtTanggalAkhir.setDate(DateNow);

            txtTanggalAkhir.setVisible(false);
            lblTo.setVisible(false);
            txtTanggalAkhir.setVisible(true);
            lblTo.setVisible(true);
        }
        else if(cbSorting.getSelectedIndex() == 1){
            
             SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy");
        txtTanggalAwal.setDateFormatString("MMMM yyyy");
              txtTanggalAkhir.setVisible(false);
            lblTo.setVisible(false);
        }
        else{
             SimpleDateFormat sdf = new SimpleDateFormat("d MMMM yyyy");
        txtTanggalAwal.setDateFormatString("yyyy");
            txtTanggalAkhir.setVisible(false);
            lblTo.setVisible(false);
        }
    }//GEN-LAST:event_cbSortingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariLaporan;
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel cardProduk;
    private javax.swing.JComboBox<String> cbSorting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBeli;
    private javax.swing.JLabel lblJual;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblLaba;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblSalesOrder;
    private com.toedter.calendar.JDateChooser txtTanggalAkhir;
    private com.toedter.calendar.JDateChooser txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
