/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naufal
 */
public class MenuSalesOrder extends javax.swing.JFrame {

    /**
     * Creates new form ViewSalesOrder
     */
    public MenuSalesOrder() {
        initComponents();
        tampilkanSalesOrder(txtCariSO.getText());
        konfigurasiTabelDetail();
                lblUsername.setText(Login.nama);

    }
    private String noSO, statusOrder;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesOrder = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtCariSO = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnCariProduk = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailSalesOrder = new javax.swing.JTable();
        btnHapusOrder = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnKembali1 = new javax.swing.JButton();
        createSO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(8, 63, 115));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 80));

        btnLogout.setBackground(new java.awt.Color(236, 236, 233));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, Username");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SBA Logistik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 768, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel25)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblSalesOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No SO", "Tanggal", "Asal", "Tujuan", "Customer", "Supplier", "Pegawai", "Total", "Status"
            }
        ));
        tblSalesOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalesOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalesOrder);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Detail Order");

        txtCariSO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariSOKeyPressed(evt);
            }
        });

        jLabel34.setText("Cari :");

        btnCariProduk.setText("Cari");
        btnCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdukActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("Data Sales Order");

        tblDetailSalesOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "produkId", "Produk", "Kuantitas", "Harga Beli", "Harga Jual", "Deskripsi"
            }
        ));
        jScrollPane2.setViewportView(tblDetailSalesOrder);

        btnHapusOrder.setText("Hapus Order");
        btnHapusOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCariSO, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCariSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCariProduk)
                        .addComponent(jLabel34))
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusOrder)
                .addGap(3, 3, 3)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(8, 63, 115));

        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });

        createSO.setText("Tambah");
        createSO.setName(""); // NOI18N
        createSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKembali1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(createSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(createSO)
                .addGap(26, 26, 26)
                .addComponent(btnKembali1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void tampilkanSalesOrder(String cari) {
    List<SalesOrder> daftar = SalesOrder.getDataSalesOrderJoin(cari); // dari fungsi yang pakai JOIN
    String[] kolom = {"No", "Nomor SO", "Tanggal", "Asal", "Tujuan", "Customer", "Supplier", "Pegawai", "Total", "Status"};

    DefaultTableModel model = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    int no = 1;
    for (SalesOrder so : daftar) {
        String statusText = so.status == 0 ? "Belum Selesai" : "Selesai";

        Object[] rowData = {
            no++,
            so.noSO,
            so.tanggal.toString(),
            so.dikirimDari,
            so.tujuan,
        so.getCustomers().isEmpty() ? "-" : so.getCustomers().get(0).nama,
      so.getSuppliers().isEmpty() ? "-" : so.getSuppliers().get(0).nama,
      so.getPegawais().isEmpty() ? "-" : so.getPegawais().get(0).nama,

            so.hargaTotal,
            statusText
        };
        model.addRow(rowData);
    }

    tblSalesOrder.setModel(model);

    // Atur lebar kolom No (opsional)
    tblSalesOrder.getColumnModel().getColumn(0).setMinWidth(30); 
    tblSalesOrder.getColumnModel().getColumn(0).setMaxWidth(30); 
    tblSalesOrder.getColumnModel().getColumn(0).setWidth(30); 
}

    private void konfigurasiTabelDetail(){
              tblDetailSalesOrder.getColumnModel().getColumn(1).setMinWidth(0); 
    tblDetailSalesOrder.getColumnModel().getColumn(1).setMaxWidth(0);
    tblDetailSalesOrder.getColumnModel().getColumn(1).setWidth(0);
    
     tblDetailSalesOrder.getColumnModel().getColumn(0).setMinWidth(30); 
    tblDetailSalesOrder.getColumnModel().getColumn(0).setMaxWidth(30); 
    tblDetailSalesOrder.getColumnModel().getColumn(0).setWidth(30); 
    
     tblDetailSalesOrder.getColumnModel().getColumn(2).setMinWidth(180); 
    tblDetailSalesOrder.getColumnModel().getColumn(2).setMaxWidth(180); 
    tblDetailSalesOrder.getColumnModel().getColumn(2).setWidth(180); 
    
      tblDetailSalesOrder.getColumnModel().getColumn(3).setMinWidth(60); 
    tblDetailSalesOrder.getColumnModel().getColumn(3).setMaxWidth(60); 
    tblDetailSalesOrder.getColumnModel().getColumn(3).setWidth(60);
    
          tblDetailSalesOrder.getColumnModel().getColumn(4).setMinWidth(100); 
    tblDetailSalesOrder.getColumnModel().getColumn(4).setMaxWidth(100); 
    tblDetailSalesOrder.getColumnModel().getColumn(4).setWidth(100);
    
      tblDetailSalesOrder.getColumnModel().getColumn(5).setMinWidth(100); 
    tblDetailSalesOrder.getColumnModel().getColumn(5).setMaxWidth(100); 
    tblDetailSalesOrder.getColumnModel().getColumn(5).setWidth(100);
    }
    
    private void tampilkanDetailOrder(String NoSo) {
    List<DetailOrder> daftarDetail = DetailOrder.getDetailJoinByNoSO(NoSo); // dari fungsi yang pakai JOIN
    String[] kolom = {"No", "Id","Produk", "Kuantitas", "Harga Beli", "Harga Jual", "Deskripsi"};

    DefaultTableModel model = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    int no = 1;
    for (DetailOrder d : daftarDetail) {

        Object[] rowData = {
            no++,
            d.id,
            d.namaProduk,
            d.kuantitas,
            d.hargaBeli,
            d.hargaJual, // Pastikan namaCustomer ditambahkan di class SalesOrder
            d.deskripsi,
        };
        model.addRow(rowData);
    }

    tblDetailSalesOrder.setModel(model);


   konfigurasiTabelDetail();
    
  
}
    
    private void createSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSOActionPerformed
        // TODO add your handling code here:
          AddSalesOrder asd = new AddSalesOrder();
            asd.setVisible(true);
            dispose();
    }//GEN-LAST:event_createSOActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda ingin logout?",
            "Logout",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        // TODO add your handling code here:
        PenjualanMenu pnj = new PenjualanMenu();
        pnj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void txtCariSOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSOKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariSOKeyPressed

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        // TODO add your handling code here:
                tampilkanSalesOrder(txtCariSO.getText());

    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnHapusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrderActionPerformed
        // TODO add your handling code here:
         if(noSO.isEmpty()){
             JOptionPane.showMessageDialog(this, "Pilih order terlebih dahulu!", "Error", JOptionPane.WARNING_MESSAGE);
             return;
        }
         if(statusOrder.equals("Selesai")){
             JOptionPane.showMessageDialog(this, "Order sudah selesai tidak dapat dihapus!", "Error", JOptionPane.WARNING_MESSAGE);
             return;
        }
         
   int pilihan = JOptionPane.showConfirmDialog(
    null,
    "Apakah anda ingin menghapus data tersebut?",
    "Hapus",
    JOptionPane.OK_CANCEL_OPTION,
    JOptionPane.WARNING_MESSAGE
);

if (pilihan == JOptionPane.OK_OPTION) {
    SalesOrder.deleteSO(noSO);
    JOptionPane.showMessageDialog(this, "Berhasil menghapus order!", "Alert", JOptionPane.INFORMATION_MESSAGE);

    tampilkanSalesOrder(txtCariSO.getText());
    DefaultTableModel model = (DefaultTableModel) tblDetailSalesOrder.getModel();
    model.setRowCount(0); // ini akan menghapus semua baris dari tabel

}
    }//GEN-LAST:event_btnHapusOrderActionPerformed

    private void tblSalesOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalesOrderMouseClicked
        // TODO add your handling code here:
        int row = tblSalesOrder.getSelectedRow();
        if (row != -1) {
            // Ambil nilai No SO dari baris yang diklik
            noSO = tblSalesOrder.getValueAt(row, 1).toString(); // asumsikan kolom ke-1 adalah no_so
            statusOrder = tblSalesOrder.getValueAt(row, 9).toString();
            tampilkanDetailOrder(noSO);
        }
        

    }//GEN-LAST:event_tblSalesOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSalesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuSalesOrder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnHapusOrder;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton createSO;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblDetailSalesOrder;
    private javax.swing.JTable tblSalesOrder;
    private javax.swing.JTextField txtCariSO;
    // End of variables declaration//GEN-END:variables
}
