/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.sql.Date;

import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author surya
 */
public class ViewKwitansi extends javax.swing.JFrame {

    /**
     * Creates new form ViewKwitansi
     */
    public ViewKwitansi() {
        initComponents();
        tampilkanKwitansi(txtCariKwitansi.getText());
         lblUsername.setText(Login.nama);
         loadInvoiceToComboBox();
        AutoCompleteDecorator.decorate(cbInvoice);
        cbInvoice.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnKembali2 = new javax.swing.JButton();
        btnTambahKwitansi = new javax.swing.JButton();
        cardProduk = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKwitansi = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbMetodeBayar = new javax.swing.JComboBox<>();
        txtKwitansi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSimpanKwitansi = new javax.swing.JButton();
        btnResetKwitansi = new javax.swing.JButton();
        btnUbahKwitansi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCariKwitansi = new javax.swing.JTextField();
        btnCariKwitansi = new javax.swing.JButton();
        txtTotalBayar = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        cbInvoice = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(8, 63, 115));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 80));

        btnLogout.setBackground(new java.awt.Color(236, 236, 233));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, Username");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SBA Logistik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel25)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(8, 63, 115));

        btnKembali2.setText("Kembali");
        btnKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali2ActionPerformed(evt);
            }
        });

        btnTambahKwitansi.setText("Tambah");
        btnTambahKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKwitansiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKembali2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnTambahKwitansi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnTambahKwitansi)
                .addGap(27, 27, 27)
                .addComponent(btnKembali2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardProduk.setBackground(new java.awt.Color(255, 255, 255));

        tblKwitansi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nomor Kwitansi", "Nomor Invoice", "Tanggal", "Metode Bayar", "Catatan", "Total Bayar"
            }
        ));
        tblKwitansi.setCellSelectionEnabled(true);
        tblKwitansi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKwitansiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKwitansi);

        jLabel9.setText("No. Kwitansi :");

        jLabel10.setText("Tanggal :");

        jLabel11.setText("Metode Bayar :");

        jLabel12.setText("Catatan :");

        cbMetodeBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Metode Bayar", "Cash", "Transfer Bank" }));
        cbMetodeBayar.setEnabled(false);
        cbMetodeBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodeBayarActionPerformed(evt);
            }
        });

        txtKwitansi.setEnabled(false);
        txtKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKwitansiActionPerformed(evt);
            }
        });

        jLabel13.setText("Total Bayar :");

        btnSimpanKwitansi.setText("Simpan");
        btnSimpanKwitansi.setEnabled(false);
        btnSimpanKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKwitansiActionPerformed(evt);
            }
        });

        btnResetKwitansi.setText("Reset");
        btnResetKwitansi.setEnabled(false);
        btnResetKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKwitansiActionPerformed(evt);
            }
        });

        btnUbahKwitansi.setText("Ubah");
        btnUbahKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKwitansiActionPerformed(evt);
            }
        });

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        txtCatatan.setEnabled(false);
        jScrollPane3.setViewportView(txtCatatan);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Data Kwitansi");

        jLabel34.setText("Cari  :");

        txtCariKwitansi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKwitansiKeyPressed(evt);
            }
        });

        btnCariKwitansi.setText("Cari");
        btnCariKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKwitansiActionPerformed(evt);
            }
        });

        txtTotalBayar.setEnabled(false);

        jLabel15.setText("No. Invoice :");

        txtTanggal.setEnabled(false);

        cbInvoice.setEnabled(false);
        cbInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardProdukLayout = new javax.swing.GroupLayout(cardProduk);
        cardProduk.setLayout(cardProdukLayout);
        cardProdukLayout.setHorizontalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addGap(25, 25, 25)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKwitansi)
                            .addComponent(cbInvoice, 0, 196, Short.MAX_VALUE)
                            .addComponent(cbMetodeBayar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                                .addComponent(btnSimpanKwitansi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetKwitansi))
                            .addComponent(jScrollPane3)
                            .addGroup(cardProdukLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUbahKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardProdukLayout.setVerticalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCariKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariKwitansi)
                            .addComponent(jLabel34)))
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbahKwitansi)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMetodeBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14)))
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetKwitansi)
                            .addComponent(btnSimpanKwitansi))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInvoiceActionPerformed

    private void btnCariKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKwitansiActionPerformed
        // TODO add your handling code here:
        tampilkanKwitansi(txtCariKwitansi.getText());
    }//GEN-LAST:event_btnCariKwitansiActionPerformed

    private void txtCariKwitansiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKwitansiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKwitansiKeyPressed

    private void btnUbahKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKwitansiActionPerformed
        // TODO add your handling code here:
        if(txtKwitansi.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        setFormKwitansiMode(true);
    }//GEN-LAST:event_btnUbahKwitansiActionPerformed

    private void btnResetKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKwitansiActionPerformed
        clearForm();
        setFormKwitansiMode(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetKwitansiActionPerformed

    private void btnSimpanKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKwitansiActionPerformed
        // TODO add your handling code here:
         if(cbMetodeBayar.getSelectedItem().toString() == "Pilih Metode Bayar"){
                    JOptionPane.showMessageDialog(this, "Pilih Metode Bayar!", "Info", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
         if(txtTanggal.getDate() == null){
                    JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!", "Info", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
          
         String noInv=cbInvoice.getSelectedItem().toString();
        Date sqlTanggal = new Date(txtTanggal.getDate().getTime());
        Kwitansi kwt = new Kwitansi("KWT-"+noInv.substring(noInv.length()-4) , noInv, cbMetodeBayar.getSelectedItem().toString(), sqlTanggal, txtCatatan.getText(), Long.parseLong(txtTotalBayar.getValue().toString()));
         kwt.updateKwitansi();
        JOptionPane.showMessageDialog(this, "Kwitansi Berhasil disimpan", "Info", JOptionPane.INFORMATION_MESSAGE);
       
            tampilkanKwitansi("");
            setFormKwitansiMode(false);
            clearForm();

    }//GEN-LAST:event_btnSimpanKwitansiActionPerformed

    private void txtKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKwitansiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKwitansiActionPerformed

    private void cbMetodeBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodeBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetodeBayarActionPerformed

    private void tblKwitansiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKwitansiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblKwitansi.getModel();
        int selectedIndexRow = tblKwitansi.getSelectedRow();

        if (selectedIndexRow != -1) { // pastikan ada yang dipilih
            txtKwitansi.setText(model.getValueAt(selectedIndexRow, 1).toString());
            cbInvoice.setSelectedItem(model.getValueAt(selectedIndexRow, 3).toString());
            String noInvoice = model.getValueAt(selectedIndexRow, 2).toString();
            for (int i = 0; i < cbInvoice.getItemCount(); i++) {
                Invoice p = (Invoice) cbInvoice.getItemAt(i);
                if (p.noInvoice.equals(noInvoice)) {
                    cbInvoice.setSelectedIndex(i);
                    break;
                }
            }

           txtTanggal.setDate((Date) model.getValueAt(selectedIndexRow, 3));

             cbMetodeBayar.setSelectedItem(model.getValueAt(selectedIndexRow, 4).toString());

            txtCatatan.setText(model.getValueAt(selectedIndexRow, 5).toString());
            txtTotalBayar.setValue(Long.parseLong(model.getValueAt(selectedIndexRow, 6).toString()));

        }
    }//GEN-LAST:event_tblKwitansiMouseClicked

    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
        PenjualanMenu pnj = new PenjualanMenu();
        pnj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembali2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda ingin logout?",
            "Logout",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTambahKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKwitansiActionPerformed
        // TODO add your handling code here:

        AddKwitansi adk = new AddKwitansi();
        adk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTambahKwitansiActionPerformed
     public void setFormKwitansiMode(Boolean flag){
//        txtIdKwitansi.setEnabled(flag);
//        cbInvoice.setEnabled(flag);
//        txtTanggal.setEnabled(flag);
//
//        cbMetodeBayar.setEnabled(flag);
        txtCatatan.setEnabled(flag);

//        txtTotalBayar.setEnabled(flag);
        btnSimpanKwitansi.setEnabled(flag);
        btnResetKwitansi.setEnabled(flag);
        
        btnUbahKwitansi.setEnabled(!flag);
        
         if (!flag) {
        // Hapus isi form saat nonaktif
       clearForm();
    }
   }
   public void clearForm(){
       
        txtKwitansi.setText("");    
        
//        if (cbInvoice.getItemCount() > 0) {
//           cbInvoice.setSelectedIndex(0);
//        }
//        else{
            cbInvoice.setSelectedItem(null);
//        }
        txtTanggal.setDate(null);
        cbMetodeBayar.setSelectedIndex(0);
        txtTotalBayar.setValue(0);
        txtCatatan.setText("");
      
   }
     private void tampilkanKwitansi(String cari) {
    List<Kwitansi> daftar = Kwitansi.getDataKwitansi(cari, null);
    String[] kolom = {"No", "No Kwitansi", "No Invoice", "Tanggal","Metode Bayar", "Catatan", "Total Bayar"};

    // Buat model tabel yang tidak bisa diedit
    DefaultTableModel model = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    int i = 0;
    for (Kwitansi k : daftar) {
        Object[] row = {
            ++i,
            k.noKwitansi,
            k.noInvoice,
                        k.tanggal,

            k.metodeBayar,
            k.catatan,
           k.totalBayar
        };
        model.addRow(row);
    }

    tblKwitansi.setModel(model); // set model baru ke JTable

    // Lebar kolom 'No' dibatasi agar kecil
    tblKwitansi.getColumnModel().getColumn(0).setMinWidth(30);
    tblKwitansi.getColumnModel().getColumn(0).setMaxWidth(30);
    tblKwitansi.getColumnModel().getColumn(0).setWidth(30);
}

            private void loadInvoiceToComboBox() {
                
                
    cbInvoice.removeAllItems(); // kosongkan dulu
    
        List<Invoice> daftar = Invoice.getDataInvoiceWithStatus("", null);
    for (Invoice d : daftar) {
        cbInvoice.addItem(d);
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKwitansi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariKwitansi;
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResetKwitansi;
    private javax.swing.JButton btnSimpanKwitansi;
    private javax.swing.JButton btnTambahKwitansi;
    private javax.swing.JButton btnUbahKwitansi;
    private javax.swing.JPanel cardProduk;
    private javax.swing.JComboBox<Invoice> cbInvoice;
    private javax.swing.JComboBox<String> cbMetodeBayar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblKwitansi;
    private javax.swing.JTextField txtCariKwitansi;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtKwitansi;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JSpinner txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
