/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

/**
 *
 * @author LOVIANNO
 */

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
public class ViewInvoice extends javax.swing.JFrame {

    /**
     * Creates new form ViewInvoice
     */
    public ViewInvoice() {
        initComponents();
        lblUsername.setText(Login.nama);
        tampilkanInvoice("");
        loadSOToComboBox();
                cbNoSO.setSelectedItem(null);
        AutoCompleteDecorator.decorate(cbNoSO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnLogout2 = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnKembali2 = new javax.swing.JButton();
        btnTambahInvoice = new javax.swing.JButton();
        cardProduk = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoInvoice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSimpanInvoice = new javax.swing.JButton();
        btnResetInvoice = new javax.swing.JButton();
        btnUbahInvoice = new javax.swing.JButton();
        btnHapusInvoice = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCariInvoice = new javax.swing.JTextField();
        btnCariInvoice = new javax.swing.JButton();
        txtTotalHarga = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        cbNoSO = new javax.swing.JComboBox<>();
        txtJatem = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(8, 63, 115));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 80));

        btnLogout2.setBackground(new java.awt.Color(236, 236, 233));
        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnLogout2.setText("Logout");
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, Username");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SBA Logistik");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel27)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(8, 63, 115));

        btnKembali2.setText("Kembali");
        btnKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali2ActionPerformed(evt);
            }
        });

        btnTambahInvoice.setText("Tambah");
        btnTambahInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKembali2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnTambahInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnTambahInvoice)
                .addGap(18, 18, 18)
                .addComponent(btnKembali2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardProduk.setBackground(new java.awt.Color(255, 255, 255));

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nomor Invoice", "Nomor SO", "Tanggal", "Jatuh Tempo"
            }
        ));
        tblInvoice.setCellSelectionEnabled(true);
        tblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvoiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInvoice);

        jLabel9.setText("No. Invoice :");

        jLabel10.setText("Tgl. Invoice :");

        txtNoInvoice.setEnabled(false);
        txtNoInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoInvoiceActionPerformed(evt);
            }
        });

        jLabel13.setText("Total Harga :");

        btnSimpanInvoice.setText("Simpan");
        btnSimpanInvoice.setEnabled(false);
        btnSimpanInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanInvoiceActionPerformed(evt);
            }
        });

        btnResetInvoice.setText("Reset");
        btnResetInvoice.setEnabled(false);
        btnResetInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetInvoiceActionPerformed(evt);
            }
        });

        btnUbahInvoice.setText("Ubah");
        btnUbahInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahInvoiceActionPerformed(evt);
            }
        });

        btnHapusInvoice.setText("Hapus");
        btnHapusInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusInvoiceActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Data Invoice");

        jLabel34.setText("Cari  :");

        txtCariInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariInvoiceKeyPressed(evt);
            }
        });

        btnCariInvoice.setText("Cari");
        btnCariInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariInvoiceActionPerformed(evt);
            }
        });

        txtTotalHarga.setEnabled(false);

        jLabel15.setText("No. Sales Order :");

        txtTanggal.setEnabled(false);

        cbNoSO.setEnabled(false);
        cbNoSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoSOActionPerformed(evt);
            }
        });

        txtJatem.setEnabled(false);

        jLabel16.setText("Tgl. Jatuh Tempo :");

        javax.swing.GroupLayout cardProdukLayout = new javax.swing.GroupLayout(cardProduk);
        cardProduk.setLayout(cardProdukLayout);
        cardProdukLayout.setHorizontalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(cardProdukLayout.createSequentialGroup()
                                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoInvoice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNoSO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardProdukLayout.createSequentialGroup()
                                        .addComponent(btnSimpanInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnResetInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardProdukLayout.createSequentialGroup()
                                .addComponent(btnUbahInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapusInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJatem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        cardProdukLayout.setVerticalGroup(
            cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdukLayout.createSequentialGroup()
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCariInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariInvoice)
                            .addComponent(jLabel34)))
                    .addGroup(cardProdukLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusInvoice)
                    .addComponent(btnUbahInvoice))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNoInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbNoSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProdukLayout.createSequentialGroup()
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtJatem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(cardProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanInvoice)
                            .addComponent(btnResetInvoice))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cardProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void setFormKwitansiMode(Boolean flag){
//        txtNoInvoice.setEnabled(flag);
        txtTanggal.setEnabled(flag);

        cbNoSO.setEnabled(flag);
        txtTanggal.setEnabled(flag);
        txtJatem.setEnabled(flag);    

//        txtTotalHarga.;
        btnSimpanInvoice.setEnabled(flag);
        btnResetInvoice.setEnabled(flag);
        
        btnUbahInvoice.setEnabled(!flag);
//        btnTambahInvoice.setEnabled(!flag);
        btnHapusInvoice.setEnabled(!flag);
        
         if (!flag) {
        // Hapus isi form saat nonaktif
       clearForm();
    }
   }
   public void clearForm(){
       
        txtNoInvoice.setText("");    
        
//        if (cbNoSO.getItemCount() > 0) {
//           cbNoSO.setSelectedIndex(0);
//        }
//        else{
            cbNoSO.setSelectedItem(null);
//        }
        
        txtTanggal.setDate(null);
        txtTotalHarga.setValue(0);
                txtJatem.setDate(null);

      
   }
   
    private void loadSOToComboBox() {
                
                
    cbNoSO.removeAllItems(); // kosongkan dulu
    
        List<SalesOrder> daftar = SalesOrder.getDataSalesOrderJoin("");
    for (SalesOrder s : daftar) {
        cbNoSO.addItem(s);
        }
    }
   
     private void tampilkanInvoice(String cari) {
    List<Invoice> daftar = Invoice.getDataInvoice(cari);
    String[] kolom = {"No", "No Invoice", "Nomor SO",  "Tanggal", "Jatuh Tempo"};

    // Buat model tabel yang tidak bisa diedit
    DefaultTableModel model = new DefaultTableModel(kolom, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    int i = 0;
    for (Invoice inv : daftar) {
        Object[] row = {
            ++i,
            inv.noInvoice,
            inv.noSO,
            inv.tanggalInvoice,
            inv.tanggalJatuhTempo   
        };
        model.addRow(row);
    }

    tblInvoice.setModel(model); // set model baru ke JTable

    // Lebar kolom 'No' dibatasi agar kecil
    tblInvoice.getColumnModel().getColumn(0).setMinWidth(30);
    tblInvoice.getColumnModel().getColumn(0).setMaxWidth(30);
    tblInvoice.getColumnModel().getColumn(0).setWidth(30);
}
    
    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda ingin logout?",
            "Logout",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
        PenjualanMenu pnj = new PenjualanMenu();
        pnj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembali2ActionPerformed

    private void txtNoInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoInvoiceActionPerformed

    private void btnSimpanInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanInvoiceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSimpanInvoiceActionPerformed

    private void btnResetInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetInvoiceActionPerformed
        clearForm();
        setFormKwitansiMode(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetInvoiceActionPerformed

    private void btnTambahInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahInvoiceActionPerformed
        // TODO add your handling code here:
//        clearForm();
//        setFormKwitansiMode(true);
AddInvoice addInvoice = new AddInvoice();
addInvoice.setVisible(true);
    }//GEN-LAST:event_btnTambahInvoiceActionPerformed

    private void btnUbahInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahInvoiceActionPerformed
        // TODO add your handling code here:
//        if(txtIdKwitansi.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        setFormKwitansiMode(true);
    }//GEN-LAST:event_btnUbahInvoiceActionPerformed

    private void btnHapusInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusInvoiceActionPerformed
        // TODO add your handling code here:
        if(txtNoInvoice.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah anda ingin menghapus data tersebut?",
            "Hapus",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (pilihan == JOptionPane.OK_OPTION) {
            Produk.deleteProduk(Integer.parseInt(txtNoInvoice.getText()));
            JOptionPane.showMessageDialog(this, "Berhasil menghapus produk!", "Alert", JOptionPane.INFORMATION_MESSAGE);
//            setFormKwitansiMode(false);
//            clearForm();

            //            tampikanProduk(txtCariKwitansi.getText());
        }
    }//GEN-LAST:event_btnHapusInvoiceActionPerformed

    private void txtCariInvoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariInvoiceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariInvoiceKeyPressed

    private void btnCariInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariInvoiceActionPerformed
        // TODO add your handling code here:
//        tampilkanKwitansi(txtCariKwitansi.getText());
    }//GEN-LAST:event_btnCariInvoiceActionPerformed

    private void cbNoSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoSOActionPerformed
        // TODO add your handling code here:
          SalesOrder selected = (SalesOrder)cbNoSO.getSelectedItem();
    if (selected != null) {
      
        txtTotalHarga.setValue( selected.hargaTotal);
    }
    }//GEN-LAST:event_cbNoSOActionPerformed

    private void tblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblInvoice.getModel();
    int selectedIndexRow = tblInvoice.getSelectedRow();

    if (selectedIndexRow != -1) {
        // Ambil nilai dari tabel
        String noInvoice = model.getValueAt(selectedIndexRow, 1).toString();
        String noSO = model.getValueAt(selectedIndexRow, 2).toString();

        // Set nilai ke field
        txtNoInvoice.setText(noInvoice);

        // Pilih item combo box berdasarkan objek SalesOrder
        for (int i = 0; i < cbNoSO.getItemCount(); i++) {
            SalesOrder s = (SalesOrder) cbNoSO.getItemAt(i);
            if (s.noSO.equals(noSO)) {
                cbNoSO.setSelectedIndex(i);
                break;
            }
        }

        // Set tanggal invoice
        Object tanggalObj = model.getValueAt(selectedIndexRow, 3); // kolom 3 = tanggal_invoice
        if (tanggalObj instanceof java.sql.Date) {
            java.util.Date tanggalUtil = new java.util.Date(((java.sql.Date) tanggalObj).getTime());
            txtTanggal.setDate(tanggalUtil);
        }

        // Set tanggal jatuh tempo
        Object tempoObj = model.getValueAt(selectedIndexRow, 4); // kolom 4 = tanggal_jatuh_tempo
        if (tempoObj instanceof java.sql.Date) {
            java.util.Date tempoUtil = new java.util.Date(((java.sql.Date) tempoObj).getTime());
            txtJatem.setDate(tempoUtil); // jika ada field jatuh tempo
        }
    }
    }//GEN-LAST:event_tblInvoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariInvoice;
    private javax.swing.JButton btnHapusInvoice;
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnResetInvoice;
    private javax.swing.JButton btnSimpanInvoice;
    private javax.swing.JButton btnTambahInvoice;
    private javax.swing.JButton btnUbahInvoice;
    private javax.swing.JPanel cardProduk;
    private javax.swing.JComboBox<SalesOrder> cbNoSO;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtCariInvoice;
    private com.toedter.calendar.JDateChooser txtJatem;
    private javax.swing.JTextField txtNoInvoice;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JSpinner txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
